version: '3.1'

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234 # ここにrootユーザーのパスワードを設定
      MYSQL_DATABASE: mydatabase  # オプション: 初期データベースの作成
      MYSQL_USER: user            # オプション: 新しいユーザーの作成
      MYSQL_PASSWORD: password    # 上記ユーザーのパスワード
    ports:
      - "3306:3306" # ホストのポートをコンテナのポートにマッピング
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - my_db:/var/lib/mysql

volumes:
  my_db:
